# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='surepy',
    version='0.4.0-beta.3',
    description='Library to interact with the flaps & doors from Sure Petcare.',
    python_requires='==3.*,>=3.8.0',
    project_urls={
        "documentation": "https://surepy.readthedocs.io",
        "homepage": "https://github.com/benleb/surepy",
        "repository": "https://github.com/benleb/surepy"
    },
    author='Ben Lebherz',
    author_email='git@benleb.de',
    license='MIT',
    keywords='cat surepetcare home-assistant',
    classifiers=[
        'Topic :: Home Automation', 'Topic :: Software Development',
        'Topic :: Software Development :: Libraries :: Python Modules',
        'Intended Audience :: Developers',
        'Intended Audience :: End Users/Desktop',
        'Operating System :: OS Independent', 'Environment :: Console',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Development Status :: 4 - Beta',
        'Development Status :: 5 - Production/Stable'
    ],
    entry_points={"console_scripts": ["surepy = surepy.cli:cli"]},
    packages=['surepy'],
    package_dir={"": "."},
    package_data={"surepy": ["*.typed"]},
    install_requires=[
        'aiohttp[speedups]==3.*,>=3.6.3', 'async-timeout==3.*,>=3.0.1',
        'colorama==0.*,>=0.4.4', 'halo==0.*,>=0.0.30', 'requests==2.*,>=2.24.0',
        'rich==9.*,>=9.1.0'
    ],
    extras_require={
        "dev": [
            "bandit==1.*,>=1.6.2", "black==20.*,>=20.8.0.b1",
            "flake8==3.*,>=3.8.4", "isort==5.*,>=5.6.4", "mypy==0.*,>=0.790.0",
            "pycodestyle==2.*,>=2.6.0", "sphinx==3.*,>=3.2.1",
            "sphinxcontrib-napoleon==0.*,>=0.7.0"
        ]
    },
)
